CREATE TABLE TRANSACTIONS(
    TRANSID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    USERID INT NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    TYPE TRANSACTION_TYPE NOT NULL,
    DATE DATE DEFAULT CURRENT_DATE,
    COMPLETED BOOLEAN NOT NULL
)